"""drop user_consents

Retires the consent gate's storage (see
docs/implementation_plans/2026-08-01-consent-simplification.md). Nothing has
written to this table since the gate came out earlier in the same change, and
the acceptance timestamps were copied into Clerk's `legalAcceptedAt` by
backend/scripts/clerk_legal_backfill.py **before this merges** — that ordering
is a hard precondition, not a preference: this migration destroys the script's
only source of data.

What is permanently given up: which policy versions each pre-Clerk user
accepted, plus the IP address and user agent captured at acceptance. Clerk
retains the timestamp alone.

The autogenerated `search_vector` index drops were removed by hand. Those GIN
indexes are created by migration c07d5e217ca3 and the ORM deliberately does not
model them, so autogenerate reported them as removed. Dropping them would not
break search — results stay correct — but it would remove GIN acceleration and
force sequential scans across bookmarks, notes, and prompts. This was the third
hand-catch, so `env.py` now filters them via `include_object`; the removal here
is retained as the record of why.

Revision ID: 6e589ceca42e
Revises: 867f3d604c7c
Create Date: 2026-08-01 21:52:16.117088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e589ceca42e'
down_revision: Union[str, Sequence[str], None] = '867f3d604c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')


def downgrade() -> None:
    """Downgrade schema."""
    # Recreates the table's shape only. The rows are NOT recoverable by
    # downgrade — this is a data-destroying migration.
    op.create_table('user_consents',
    sa.Column('consented_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Timestamp when user accepted the terms'),
    sa.Column('privacy_policy_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="Version of privacy policy accepted (e.g., '2024-12-20')"),
    sa.Column('terms_of_service_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment="Version of terms of service accepted (e.g., '2024-12-20')"),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True, comment='IP address at time of consent (for legal proof)'),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True, comment='Browser user agent at time of consent (for legal proof)'),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='Foreign key to users table - one consent record per user'),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_consents_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_consents_pkey'))
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=True)
